### ISSUE TITLE
Cross-locale configuration

### ISSUE THREAD

**Issue by narkuss** [Alfresco/SearchServices#251]
That's not exactly an issue but a feature petition.

We've been dealing with this for a year. I don't know why cross-locale is not enabled by default, I imagine there will be reasons to do so, but please, provide at least an environment variable to activate it from docker configuration, so we don't have to override default Dockerfile, or provide additional volumes with modified shared.properties file.

Thanks

**Comment by aborroy** [comment]
We have this feature identified as:
https://issues.alfresco.com/jira/browse/SEARCH-1605

**Comment by narkuss** [comment]
Ok, nice! 
Sorry, I should have searched before posting the issue...

**Comment by hi-ko** [comment]
Maybe the wrong ticket, but I would vote for a complete non-cross-locale environment since the repository locale handling is more confusing than helpful. At least the search and indexing behavior is not as expected by the user since the assumptions Alfresco does to choose the locale does not corelate to the doc's language. So we can't trust the locale decision done by Alfresco in many/most cases we patched as a work around the repo to always choose the same one and only configured default language the server is running on. s. https://github.com/ecm4u/alfresco-data-model/issues/1

Of course this would (re)start the discussion how to stem and handle stopwords but since the stemming and stopword selection is done today somehow by accident and for the user perception evertime different we would prefer no stemming / stopwording as long alfresco has no reliable mechanism in place to identify the language of the content.

**Comment by iseks** [comment]
I'd like to renew the request on the exact reason why, the following entries in `solrhome/conf/shared.properties`  are commented out by default (community docker images):
`
# Data types that support cross locale/word splitting/token patterns if tokenised
#alfresco.cross.locale.datatype.0={http://www.alfresco.org/model/dictionary/1.0}text
#alfresco.cross.locale.datatype.1={http://www.alfresco.org/model/dictionary/1.0}content
#alfresco.cross.locale.datatype.2={http://www.alfresco.org/model/dictionary/1.0}mltext
`
Unfortunately the link to the issue as commented by [aborroy](https://github.com/aborroy) a couple of years ago is not accessible anymore.

When those cross-locale options are disabled in Alfresco Community Edition, full-text search filters out results based on locale mismatches between content and browser settings.

This happens, e.g. when content is uploaded by WebDAV and searched with a browser with German localization:
 
 -  WebDAV uploads: Content nodes receive locale "en_"
 -  Browser uploads (e.g., Firefox): Content nodes receive locale "de_"
 -  Search behavior: Only displays results where text content locale matches the browser's request locale

Although Alfresco Community Edition lacks default multi-language support, it still assigns and stores locale with content. The search engine then restricts results to content matching the requesting browser's locale, effectively filtering out otherwise relevant documents uploaded via different methods.

If those settings are enabled, full text search works as expected, also for documents which are uploaded by WebDAV.

It took hours of research to find out, why alfresco dropped important documents from full-text search. For users, who use community edition in e.g. Germany using also WebDAV this makes alfresco unusable, if those options are turned off.

I'd propose to enable those options by default or improve documentation if there are significant reasons to keep those options disabled by default.
